# Generated by Django 4.2.3 on 2023-07-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
