# Generated by Django 4.2.3 on 2023-07-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
